
const RoutePath = {

  LOGIN: `${process.env.PUBLIC_URL}/`,
  TOOLLOGIN: `${process.env.PUBLIC_URL}/ToolLogin`,
  FORGOT: `${process.env.PUBLIC_URL}/forgot`,
  SIGNUP: `${process.env.PUBLIC_URL}/signup`,
  CLIENTS: `${process.env.PUBLIC_URL}/clients`,
  CLIENTSEDIT: `${process.env.PUBLIC_URL}/ClientsEdit`,
  CREATECLIENTS: `${process.env.PUBLIC_URL}/CreateClients`,
  LISTINGS: `${process.env.PUBLIC_URL}/Listings`,
  OVERVIEW: `${process.env.PUBLIC_URL}/Overview`,
  COMPS: `${process.env.PUBLIC_URL}/Comps`,
  MASTERPROPERTY: `${process.env.PUBLIC_URL}/MasterProperties`,
  PROPERTYDETAILS: `${process.env.PUBLIC_URL}/PropertiesDetails`,
  USERPROFILE: `${process.env.PUBLIC_URL}/UserProfile`,
  ACCOUNTS: `${process.env.PUBLIC_URL}/Accounts`,
  CREATEACCOUNTS: `${process.env.PUBLIC_URL}/CreateAccount`,
  EDITACCOUNTS: `${process.env.PUBLIC_URL}/EditAccount`,
  USERLIST: `${process.env.PUBLIC_URL}/UserList`,
  CREATEUSERLIST: `${process.env.PUBLIC_URL}/CreateUserList`,
  EDITUSERLIST: `${process.env.PUBLIC_URL}/EditUserList`,
  BROKERLIST: `${process.env.PUBLIC_URL}/BrokerList`,
  USEREDITACCOUNT: `${process.env.PUBLIC_URL}/UserEditAccount`,
  SETTING: `${process.env.PUBLIC_URL}/Setting`,
  PAGELIST: `${process.env.PUBLIC_URL}/PageList`,
  CREATEPAGE: `${process.env.PUBLIC_URL}/CreatePage`,
  EDITPAGE: `${process.env.PUBLIC_URL}/EditPage`,
  MENULIST: `${process.env.PUBLIC_URL}/MenuList`,
  EDITMENULIST: `${process.env.PUBLIC_URL}/EditMenuList`,
  LISTINGSMASTERPROPERTY: `${process.env.PUBLIC_URL}/ListingsMasterProperties`,
  LISTINGSPROPERTYDETAILS: `${process.env.PUBLIC_URL}/ListingsPropertiesDetails`,
  ATTACHMENTS: `${process.env.PUBLIC_URL}/Attachments`,
  PROPERTYBOUNDARIES: `${process.env.PUBLIC_URL}/PropertyBoundaries`,
  EVALUATION: `${process.env.PUBLIC_URL}/Evaluation`,
  EVALUATIONOVERVIEW: `${process.env.PUBLIC_URL}/EvaluationOverview`,
  IMAGEPAGE: `${process.env.PUBLIC_URL}/ImagePage`,
  EVALUATIONPROPERTYBOUNDARIES: `${process.env.PUBLIC_URL}/EvaluationPropertyBoundaries`,
  EVALUATIONAERIALMAP: `${process.env.PUBLIC_URL}/EvaluationAerialMap`,
  EVALUATIONAREAINFO: `${process.env.PUBLIC_URL}/EvaluationAreaInfo`,
  EXHIBITS: `${process.env.PUBLIC_URL}/Exhibits`,
  REVIEW: `${process.env.PUBLIC_URL}/Review`,
  SALESCOMPS: `${process.env.PUBLIC_URL}/SalesComps`,
  COMPAREAMAP: `${process.env.PUBLIC_URL}/CompAreaMap`,
  BILLING: `${process.env.PUBLIC_URL}/Billing`,
  PAYMENTMETHOD: `${process.env.PUBLIC_URL}/PaymentMethod`,
}
export default RoutePath;
